version: "3"

services:

  account-database:
    image: jzaccone/account-database
    build:
      context: ./account-database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: password
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    ports:
      - "3306:3306" 
    restart: always

  compute-interest-api:
    image: jzaccone/compute-interest-api
    build: 
      context: ./compute-interest-api
    ports:
      - "8080:8080" 
    restart: always  
    depends_on:
      - "account-database"
  
  account-summary:
    image: jzaccone/account-summary
    build: 
      context: ./account-summary
    ports:
      - "5001:80"

  transaction-generator:
    image: jzaccone/transaction-generator
    build:
      context: ./transaction-generator
    restart: always

